### ISSUE TITLE
TssRename editing wrong locations in file if buffers are not saved

### ISSUE THREAD

**Issue by nicknisi** [jason0x43/vim-tss#1]
If the file has been modified, using `TssRename` will try do the renaming in the wrong location, assumingely based on the saved file location for the node position.
![tssrename](https://cloud.githubusercontent.com/assets/293805/23267043/2cd90338-f9af-11e6-817e-0d979ccebda6.gif)

**Comment by jason0x43** [comment]
The rename method in autoload does theoretically refresh all open files, but that may not be happening.

Also, it seems like TssRename only works properly if the vim session, or possibly the tsserver session, is started such that pwd === the project root.

**Comment by jason0x43** [comment]
Or possibly the file paths passed to tsserver need to be relative to the tsconfig file.

**Comment by jason0x43** [comment]
Open files weren't being record in the `open_files` list.
