### ISSUE TITLE
lwindow opens for TssDefinition

### ISSUE THREAD

**Issue by nicknisi** [jason0x43/vim-tss#2]
When `let g:tss_auto_open_loclist=1`, the lwindow gets opened up, even when using TssDefinition. Shouldn't TssDefinition really only ever have a single result? If so, having the lwindow open for this case is unnecessary.

**Comment by jason0x43** [comment]
I seem to recall it having multiple results sometimes (even thought you'd think it should only have one). I'll see if I can find a test case showing that, otherwise we can just ignore that when making a definition request.

**Comment by nicknisi** [comment]
I found an instance where there's multiple definitions, such as when an interface is extended.

![screen shot 2017-03-21 at 8 26 42 pm](https://cloud.githubusercontent.com/assets/293805/24178070/bc2c2d74-0e74-11e7-9821-b368b960aff1.png)

**Comment by jason0x43** [comment]
I went ahead and updated the plugin in 7d527ce to only open the loclist if there's more than one entry (and `tss_auto_open_loclist=1`), which should be reasonable behavior for every use case.
